### ISSUE TITLE
| Menu Index | ID Problem

### ISSUE THREAD

**Issue by pinoylifecraft** [MediusEcho/ParticleHatsWiki#1]
## Hello Owner ? Ahm I can't change the ID to 160:15 or stained_glass_pane:15 instead it will become 1 or STONE here is my menu_index.yml

items:
  # PURCHASE_ITEM will be replaced with the hat the player is purchasing
  '1':
    id: PURCHASE_ITEM
  '3':
    id: stained_glass_pane:15
    name: " "
    action: DUMMY
  '5':
    id: stained_glass_pane:5
    damage-value: 0
    name: "&a&lConfirm"
    action: PURCHASE
  '7':
    id: stained_glass_pane:14
    damage-value: 0
    name: "&4&lCancel"  
    action: NEXT_PAGE

**Comment by MediusEcho** [comment]
You need to separate your damage values from your id.

Example:
id: STAINED_GLASS_PANE
damage-value: 15

**Comment by pinoylifecraft** [comment]
Hehe Sorry Thanks it works :+1: 
id: STAINED_GLASS_PANE
damage-value: 15
