### ISSUE TITLE
[ Demo Particles ] Suggest

### ISSUE THREAD

**Issue by pinoylifecraft** [MediusEcho/ParticleHatsWiki#2]
My Suggestion :hammer: 
Can you add this ?
action: Demo or Try
and the Demo or Try action has a time limit to equip 
maybe 30 sec or customize or we can edit it on config
# This option is for demo time limit - seconds -

demotime: 30

Hope it will add soon :hammer: 
Useful for Economy if the player don't like to waste there money :dollar: 
:philippines:

**Comment by MediusEcho** [comment]
I'm currently trying to get MySQL support working. I'll add this suggestion to my list, but probably won't be releasing an update until i get MySQL working as it should.

**Comment by pinoylifecraft** [comment]
Whooooo :+1: 
Thank You so much :smile:
