### ISSUE TITLE
permissions not working

### ISSUE THREAD

**Issue by Zeke5399** [MediusEcho/ParticleHatsWiki#4]
players can open the gui and it works but they are able to use trails that i dont want them to use and when i put in a perm for it the plugin breaks. And i go to the wiki and there are no examples of what to do.

**Comment by Zeke5399** [comment]
I did not even give them the all permission and yet they have all of the trails

**Comment by MediusEcho** [comment]
Are there any errors when the plugin breaks? What permissions are you using? Do you have permissions enabled in config.yml?

**Comment by Zeke5399** [comment]
its not that but in the config there is a perm for a trail that says donor yet players can use it and i dont want them to

**Comment by Skalylikesbudder** [comment]
I even negated the perm for all trails and still they can use them all its like the dev never set them up or something idk

**Comment by Zeke5399** [comment]
oh perms are not enabled I watched the tutorial and he did not once mention that xD

**Comment by MediusEcho** [comment]
The videos on my Spigot page are more like showcases. I went ahead and cleaned up the wiki pages a little bit more to hopefully make things clearer
