### ISSUE TITLE
Server thread/ERROR null when pressing /h

### ISSUE THREAD

**Issue by Klawdek** [MediusEcho/ParticleHatsWiki#8]
After installing plugin I tried to use it and when I did /h I got this error.  I am using spigot
CraftBukkit version git-Spigot-798ea6a-4914117 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
and
ParticleHats version 4.0.0-RC3

29.08 01:14:01 [Server] Server thread/INFO Klawdek issued server command: /h
29.08 01:14:01 [Server] Server thread/ERROR null
29.08 01:14:01 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'h' in plugin ParticleHats v4.0.0-RC3
29.08 01:14:01 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot_1.14.4_latest.jar:git-Spigot-798ea6a-4914117]
29.08 01:14:01 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot_1.14.4_latest.jar:git-Spigot-798ea6a-4914117]
29.08 01:14:01 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot_1.14.4_latest.jar:git-Spigot-798ea6a-4914117]
29.08 01:14:01 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot_1.14.4_latest.jar:git-Spigot-798ea6a-4914117]
29.08 01:14:01 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot_1.14.4_latest.jar:git-Spigot-798ea6a-4914117]
29.08 01:14:01 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot_1.14.4_latest.jar:git-Spigot-798ea6a-4914117]
29.08 01:14:01 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot_1.14.4_latest.jar:git-Spigot-798ea6a-4914117]
29.08 01:14:01 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot_1.14.4_latest.jar:git-Spigot-798ea6a-4914117]
29.08 01:14:01 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot_1.14.4_latest.jar:git-Spigot-798ea6a-4914117]
29.08 01:14:01 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot_1.14.4_latest.jar:git-Spigot-798ea6a-4914117]
29.08 01:14:01 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot_1.14.4_latest.jar:git-Spigot-798ea6a-4914117]
29.08 01:14:01 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot_1.14.4_latest.jar:git-Spigot-798ea6a-4914117]
29.08 01:14:01 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot_1.14.4_latest.jar:git-Spigot-798ea6a-4914117]
29.08 01:14:01 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot_1.14.4_latest.jar:git-Spigot-798ea6a-4914117]
29.08 01:14:01 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot_1.14.4_latest.jar:git-Spigot-798ea6a-4914117]
29.08 01:14:01 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:885) [spigot_1.14.4_latest.jar:git-Spigot-798ea6a-4914117]
29.08 01:14:01 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot_1.14.4_latest.jar:git-Spigot-798ea6a-4914117]
29.08 01:14:01 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
29.08 01:14:01 [Server] INFO Caused by: java.lang.NullPointerException
29.08 01:14:01 [Server] INFO at com.mediusecho.particlehats.commands.MainCommand.execute(MainCommand.java:42) ~[?:?]
29.08 01:14:01 [Server] INFO at com.mediusecho.particlehats.commands.Command.onCommand(Command.java:78) ~[?:?]
29.08 01:14:01 [Server] INFO at com.mediusecho.particlehats.managers.CommandManager.onCommand(CommandManager.java:85) ~[?:?]
29.08 01:14:01 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot_1.14.4_latest.jar:git-Spigot-798ea6a-4914117]
29.08 01:14:01 [Server] INFO ... 17 more

**Comment by Klawdek** [comment]
I fixed the problem initially I followed the instructions and just renamed the config.yml.  What fixed the problem was renaming the particlehats directory and letting it do a fresh install.

**Comment by MediusEcho** [comment]
Thanks for letting me know about this issue. Glad you got it working.

**Comment by MediusEcho** [comment]
Fixed in the 4.0.0 release.
